resource "tetration_filter" "TAAS" {
  name         = "TAAS"
  query        = jsonencode(
            { "type": "or",
                     "filters": [ { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.157.8"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.19.206"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.149.13"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.170"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.146.69"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.145.203"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.153.200"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.94.102"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.150.231"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.153.189"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.154.177"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.169"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.73"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.144.115"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.144.212"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.94.149"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.150.150"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.88.9"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.144.213"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.155.98"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.212"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.155.97"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.88.8"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.91.0"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.19.58"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.144.214"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.91.62"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.149.132"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.10.167"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.148.77"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.19.59"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.91.85"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.171"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.157.122"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.95.162"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.145.72"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.152.70"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.150.110"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.89.182"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.95.160"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.148.211"},
                                  { "field": "ip",
                                    "type": "eq",
                                    "value": "129.146.92.7"}]}
  )
  app_scope_id = "63481c10755f0275ed2a9df5" # Internet Scope
  primary      = true
  public       = false
}